feat(ui): Add "sort by" to Network Scout
safing/portmaster-ui pull request #432
Opened 2023-04-29 12:18 UTC by SammCheese

I've found it quite odd that there was no way to sort in what order Apps are displayed.
This PR aim's to solve this by adding a Sort button and defaulting to "A - Z".

Previews attached.

![image](https://user-images.githubusercontent.com/52699291/235302071-86d4d314-ecc4-4e6e-879d-1051e1fbebd3.png)
![image](https://user-images.githubusercontent.com/52699291/235302079-1cdf3141-6690-4f9c-b9d9-d5c8db839650.png)

2023-04-29 12:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/safing/portmaster-ui?pullRequest=432) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/safing/portmaster-ui?pullRequest=432) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/safing/portmaster-ui?pullRequest=432) it.</sub>

2023-04-30 21:25 UTC, SammCheese commented
I can't add reviewers, so a manual Tagging is required.
@ppacher @dhaavi, need a review here.

2023-05-06 09:25 UTC, SammCheese commented
My apologies, pushed to the wrong branch, all changes are reverted ^^

2023-05-09 08:02 UTC, ppacher requested changes

2023-08-28 14:38 UTC, dhaavi commented
Hey @SammCheese, thanks for the great work!

@ppacher integrated this into the latest UI version, but needed to make some changes together with other fixes, so we weren't able to just merge this here - sorry about that.

Here are the relevant commits:
https://github.com/safing/portmaster-ui/pull/477/commits/3cbd79a458c2bca99071b21bf13b21667a618b29
https://github.com/safing/portmaster-ui/pull/478/commits/23b7f19e54d7637de826143cf1a5bbadc43fe264

Thanks again for this PR, it was really helpful!

2023-08-28 14:38 UTC, closed without merging