Update pilot widget
safing/portmaster-ui pull request #99
Opened 2020-12-17 12:29 UTC by LukeSeers

2020-12-17 14:37 UTC, dhaavi requested changes
I tested it an it works. 👌

I'm not quite sure why we got started with `Failure`, let's talk about that:
https://github.com/safing/portmaster-ui/blob/a3af21d55eec13cab79c85880809795afe23e591/modules/portmaster/src/app/widgets/pilot-widget/pilot-widget.ts#L114

2020-12-17 14:37 UTC, dhaavi commented on modules/portmaster/src/app/widgets/pilot-widget/pilot-widget.html
> +  <span>Running smoothly</span>
Maybe not.

2020-12-18 11:28 UTC, dhaavi approved these changes

2020-12-18 12:41 UTC, ppacher commented
The animation of the lock has a little start delay which causes the lock to look weired when first rendered. This might not be a real issue but if you start to drag the pilot widget around you "re-create" the lock at a different DOM position which will reset the animation to start. That looks a bit weird:

![animation-issue](https://user-images.githubusercontent.com/1043756/102615705-a78ce400-4136-11eb-8445-ef6e4fed0971.gif)

2020-12-18 15:01 UTC, ppacher requested changes
See other comment

2020-12-21 10:33 UTC, dhaavi approved these changes

2020-12-21 10:33 UTC, merged

2020-12-21 14:23 UTC, ppacher reviewed
LGTM